version: '3'

services:
  web:
    container_name: '${APP_CONTAINER:-laravel}'
    build:
      context: .
    ports:
       - '${APP_PORT:-80}:80'
    volumes:
      - .:/var/www/html
    # depends_on:
      # - db

    # db:
    #   image: oracleinanutshell/oracle-xe-11g
    #   environment:
    #     - ORACLE_ALLOW_REMOTE=true
    #   ports:
    #     - "1521:1521"
